services:
    web:
        build:
            context: ./
            dockerfile: web.Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        networks:
            - app-network
    app:
        build:
            context: ./
            dockerfile: app.Dockerfile
        volumes:
            - ./:/var/www
        networks:
            - app-network
    cache:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
